export { default as Eye } from './Eye'
export { default as Google } from './Google'
export { default as Google1 } from './Google1'
export { default as Lock } from './Lock'
export { default as Mail } from './Mail'